on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create a release

jobs:
  build:
    name: Create Release
    if: github.repository == 'cilium/hubble'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - name: Generate artifacts
        run: make release
      - name: Create Release
        id: create_release
        uses: actions/create-release@4c11c9fe1dcd9636620a16455165783b20fc7ea0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true # turn this to false once release notes are automatically added
          prerelease: false
          body: |
            Note for maintainers:: Please, update the desciption with the actual release notes (see RELEASE.md for instructions).
      - name: Upload artifacts 
        id: upload-release-artifacts
        uses: skx/github-action-publish-binaries@44887b225ceca96efd8a912d39c09ad70312af31
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.create_release.outputs.id }}
          args: 'release/*'
