name: Run static checks and unit tests

# Any change in triggers needs to be reflected in the concurrency group.
on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
    - master
    - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
      with:
        go-version: '1.19.9'
    - name: Run static checks
      uses: golangci/golangci-lint-action@0d51521d4226fe362fc8aa8ce484ce3cd5299478
      with:
        version: v1.50.1
        args: --config=.golangci.yml --verbose
        skip-cache: true
    - name: Check module vendoring
      run: |
        go mod tidy
        go mod vendor
        go mod verify
        git status
        test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
    - name: Run unit tests
      run: make test
    - name: Build
      run: make
    - name: Build release binaries
      run: make release
